architecture: standalone

auth:
  enabled: false  

persistence:
  enabled: true
  size: 8Gi

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi